spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nadak-by-boot
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false

logging:
  level:
    org:
      hibernate:
        type: trace